version: '3'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "5001:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/tally_subscribers
      - SECRET_KEY=${SECRET_KEY:-default_secret_key}
      - GMAIL_ADDRESS=${GMAIL_ADDRESS:-sundaihack@gmail.com}
      - GMAIL_APP_PASSWORD=${GMAIL_APP_PASSWORD}
      - TALLY_WEBHOOK_SECRET=${TALLY_WEBHOOK_SECRET}
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
    restart: unless-stopped

  mongo:
    image: mongo:5
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
