version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5001:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/tally_subscribers
      - SECRET_KEY=${SECRET_KEY:-default_secret_key}
      - GMAIL_ADDRESS=${GMAIL_ADDRESS:-sundaihack@gmail.com}
      - GMAIL_APP_PASSWORD=${GMAIL_APP_PASSWORD}
      - TALLY_WEBHOOK_SECRET=${TALLY_WEBHOOK_SECRET}
    depends_on:
      - db
    volumes:
      - ./backend:/app
    restart: unless-stopped

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tally_subscribers
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
