version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5001:5000"
    environment:
      - SECRET_KEY=${SECRET_KEY:-default_secret_key}
      - GMAIL_ADDRESS=${GMAIL_ADDRESS:-sundaihack@gmail.com}
      - GMAIL_APP_PASSWORD=${GMAIL_APP_PASSWORD}
      - TALLY_WEBHOOK_SECRET=${TALLY_WEBHOOK_SECRET}
    volumes:
      - ./backend:/app
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
