services:
  # Backend API service
  - type: web
    name: tally-subscriber-manager-api
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: starter
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: GMAIL_ADDRESS
        sync: false
      - key: GMAIL_APP_PASSWORD
        sync: false
      - key: TALLY_WEBHOOK_SECRET
        sync: false
    disk:
      name: postgres-data
      mountPath: /var/lib/postgresql/data
      sizeGB: 1
